#!/bin/bash
# Quick deployment commands - Copy and paste these into your terminal

echo "════════════════════════════════════════════════════════════════"
echo "🚀 RAILWAY DEPLOYMENT - COPY & PASTE COMMANDS"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "Run these commands in order:"
echo ""
echo "────────────────────────────────────────────────────────────────"
echo "1️⃣  LOGIN TO RAILWAY"
echo "────────────────────────────────────────────────────────────────"
echo "railway login"
echo ""
echo "────────────────────────────────────────────────────────────────"
echo "2️⃣  NAVIGATE TO PROJECT"
echo "────────────────────────────────────────────────────────────────"
echo "cd /Users/khiwn/nt-poc/nt-poc"
echo ""
echo "────────────────────────────────────────────────────────────────"
echo "3️⃣  RUN COMPLETE DEPLOYMENT"
echo "────────────────────────────────────────────────────────────────"
echo "./start-deployment.sh"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "OR run step-by-step:"
echo ""
echo "# Link project"
echo "railway link --project battery-rul-monitoring"
echo ""
echo "# Setup environment variables"
echo "./setup-shared-env.sh"
echo ""
echo "# Deploy all services"
echo "./deploy-all-services.sh"
echo ""
echo "# Verify everything"
echo "./verify-env.sh"
echo ""
echo "════════════════════════════════════════════════════════════════"
