/**
 * Generate Human-Readable Chaos Test Report
 */

import chalk from 'chalk';
import fs from 'fs/promises';

async function loadReport() {
  try {
    const data = await fs.readFile('chaos-test-report.json', 'utf-8');
    return JSON.parse(data);
  } catch (error) {
    console.error(chalk.red('Error: Could not load chaos-test-report.json'));
    console.error(chalk.red('Please run the chaos tests first: npm run test:chaos'));
    process.exit(1);
  }
}

function generateMarkdownReport(report) {
  const lines = [];
  
  lines.push('# Chaos Testing Report');
  lines.push('');
  lines.push(`**Generated:** ${new Date(report.timestamp).toLocaleString()}`);
  lines.push(`**Duration:** ${report.duration}`);
  lines.push('');
  
  lines.push('## Summary');
  lines.push('');
  lines.push(`- **Total Scenarios:** ${report.summary.totalScenarios}`);
  lines.push(`- **Scenarios Passed:** ${report.summary.scenariosPassed}`);
  lines.push(`- **Scenarios Failed:** ${report.summary.scenariosFailed}`);
  lines.push(`- **Total Tests:** ${report.summary.totalTests}`);
  lines.push(`- **Tests Passed:** ${report.summary.totalPassed}`);
  lines.push(`- **Tests Failed:** ${report.summary.totalFailed}`);
  lines.push(`- **Overall Success Rate:** ${(report.summary.overallSuccessRate * 100).toFixed(1)}%`);
  lines.push('');
  
  lines.push('## Scenarios');
  lines.push('');
  
  report.reports.forEach(scenario => {
    const status = scenario.stats.failed === 0 ? '✅ PASSED' : '❌ FAILED';
    lines.push(`### ${scenario.scenario} - ${status}`);
    lines.push('');
    lines.push(`- **Total Tests:** ${scenario.stats.total}`);
    lines.push(`- **Passed:** ${scenario.stats.passed}`);
    lines.push(`- **Failed:** ${scenario.stats.failed}`);
    lines.push(`- **Success Rate:** ${scenario.stats.passRate}`);
    lines.push('');
    
    if (scenario.results && scenario.results.length > 0) {
      lines.push('#### Test Results');
      lines.push('');
      scenario.results.forEach(result => {
        const icon = result.passed ? '✓' : '✗';
        lines.push(`- ${icon} **${result.name}** ${result.duration ? `(${result.duration}ms)` : ''}`);
        
        if (result.metrics && Object.keys(result.metrics).length > 0) {
          lines.push('  - Metrics:');
          Object.entries(result.metrics).forEach(([key, value]) => {
            lines.push(`    - ${key}: ${value}`);
          });
        }
        
        if (result.errors && result.errors.length > 0) {
          lines.push('  - Errors:');
          result.errors.forEach(error => {
            lines.push(`    - ${error.message}`);
          });
        }
      });
      lines.push('');
    }
  });
  
  lines.push('## Recommendations');
  lines.push('');
  
  const failedScenarios = report.reports.filter(r => r.stats.failed > 0);
  
  if (failedScenarios.length === 0) {
    lines.push('✅ All chaos scenarios passed! System demonstrates excellent resilience.');
  } else {
    lines.push('⚠️ Some scenarios failed. Consider the following improvements:');
    lines.push('');
    
    failedScenarios.forEach(scenario => {
      lines.push(`- **${scenario.scenario}**: Review and improve system behavior`);
      
      if (scenario.results) {
        const failedTests = scenario.results.filter(r => !r.passed);
        failedTests.forEach(test => {
          lines.push(`  - ${test.name}: ${test.errors?.[0]?.message || 'Failed'}`);
        });
      }
    });
  }
  
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push('*Generated by Chaos Testing Suite*');
  
  return lines.join('\n');
}

async function generateReport() {
  console.log(chalk.cyan('Loading chaos test results...'));
  
  const report = await loadReport();
  
  console.log(chalk.cyan('Generating report...'));
  
  const markdown = generateMarkdownReport(report);
  
  // Save markdown report
  await fs.writeFile('CHAOS_TEST_REPORT.md', markdown);
  console.log(chalk.green('✓ Markdown report saved to CHAOS_TEST_REPORT.md'));
  
  // Print summary to console
  console.log('\n' + chalk.bold('═'.repeat(60)));
  console.log(chalk.bold.cyan('CHAOS TESTING SUMMARY'));
  console.log(chalk.bold('═'.repeat(60)));
  console.log(`Timestamp: ${new Date(report.timestamp).toLocaleString()}`);
  console.log(`Duration: ${report.duration}`);
  console.log(`Scenarios: ${report.summary.scenariosPassed}/${report.summary.totalScenarios} passed`);
  console.log(`Tests: ${report.summary.totalPassed}/${report.summary.totalTests} passed`);
  console.log(`Success Rate: ${report.summary.overallSuccessRate >= 0.95 ? chalk.green((report.summary.overallSuccessRate * 100).toFixed(1) + '%') : chalk.red((report.summary.overallSuccessRate * 100).toFixed(1) + '%')}`);
  console.log(chalk.bold('═'.repeat(60)) + '\n');
}

generateReport().catch(error => {
  console.error(chalk.red('Error generating report:'), error);
  process.exit(1);
});
