[phases.setup]
nixPkgs = ["nodejs_22", "npm-9_x", "postgresql"]

[phases.install]
cmds = ["npm install --cache=/tmp/.npm --prefer-offline=false"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "bash scripts/start-production.sh"
